problem= "couette"
collision="BGK"
backend="openmp"

[lattice]
size = [129, 129, 129];

[physics]
reynolds = 100.0
init_vel = [0.1, 0, 0];

[solver]
niters = 100000
nframes = 300

[output]
frames="./out/frames_couette_openmp_d2q9.bin"
profile="./out/profile_couette_openmp_d2q9.bin"
