[[conf]]

[conf.lattice]
size = [200, 200, 200]

[conf.physics]
reynolds = 1000.0
init_vel     = [0.1, 0.0, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/frames_lid_cavity_d3q19_200_200_200_1000_01_bgk.bin"
profile = "out/profile_lid_cavity_d3q19_200_200_200_1000_01_bgk.dat"
