[problem]
type = "lid_cavity"

[grid]
nx = 129
ny = 129

[physics]
collision = "BGK"
reynolds = 100.0
init_vel_x = 0.1

[solver]
niters = 10000
nframes = 100
backend = "openmp"

[output]
path = "out"
