[[conf]]
collision = "bgk"
backend   = "openmp"

[conf.lattice]
size = [2000, 2000]

[conf.physics]
reynolds = 7500.0
init_vel     = [0.2, 0.0]

[conf.solver]
niters  = 500000
nframes = 200

[conf.output]
frames  = "out/frames_lid_cavity_d2q9_2000_2000_7500_bgk.out"
profile = "out/profile_lid_cavity_d2q9_2000_2000_7500_bgk.dat"

[[conf]]
collision = "bgk"
backend   = "openmp"

[conf.lattice]
size = [5000, 5000]

[conf.physics]
reynolds = 10000.0
init_vel     = [0.2, 0.0]

[conf.solver]
niters  = 500000
nframes = 200

[conf.output]
frames  = "out/frames_lid_cavity_d2q9_5000_5000_10000_bgk.out"
profile = "out/profile_lid_cavity_d2q9_5000_5000_10000_bgk.dat"
