[problem]
type = "poiseuille"

[grid]
nx = 129
ny = 129

[physics]
collision = "BGK"
reynolds = 100.0
init_vel_x = 0.1

[solver]
niters = 100000
nframes = 200
backend = "openmp"

[output]
path = "out"
