[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
size     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/profiling_result_dump.vtk"
profile = "out/time/profiling_result1.dat"

[conf.backend]
n_threads = 1

[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
size     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/profiling_result_dump.vtk"
profile = "out/time/profiling_result2.dat"

[conf.backend]
n_threads = 2

[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
size     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/profiling_result_dump.vtk"
profile = "out/time/profiling_result4.dat"

[conf.backend]
n_threads = 4

[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
size     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/profiling_result_dump.vtk"
profile = "out/time/profiling_result8.dat"

[conf.backend]
n_threads = 8

[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
size     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/profiling_result_dump.vtk"
profile = "out/time/profiling_result16.dat"

[conf.backend]
n_threads = 16
