[[conf]]

[conf.lattice]
size = [129, 129]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result1.dat"

[conf.backend]
n_threads = 1

[[conf]]

[conf.lattice]
size = [183, 183]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result2.dat"

[conf.backend]
n_threads = 2

[[conf]]

[conf.lattice]
size = [257, 257]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result4.dat"

[conf.backend]
n_threads = 4

[[conf]]

[conf.lattice]
size = [365, 365]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result8.dat"

[conf.backend]
n_threads = 8

[[conf]]

[conf.lattice]
size = [515, 515]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result16.dat"

[conf.backend]
n_threads = 16


[[conf]]

[conf.lattice]
size = [1000, 1000]

[conf.physics]
reynolds = 100.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result32.dat"

[conf.backend]
n_threads = 32


[[conf]]

[conf.lattice]
size = [2000, 2000]

[conf.physics]
reynolds = 1000.0
init_vel     = [0.1, 0.0]

[conf.solver]
niters  = 100000
nframes = 200

[conf.output]
frames  = "out/weak_dump.out"
profile = "out/time/weak_result64.dat"

[conf.backend]
n_threads = 64
